name: expense_tracker_app
description: "现代化移动端个人记账应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # UI组件和图标
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  
  # 图表库
  fl_chart: ^0.65.0
  
  # 动画
  animations: ^2.0.8
  lottie: ^2.7.0
  
  # 本地存储
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # 日期时间处理
  intl: ^0.18.1
  
  # 语音识别
  speech_to_text: ^6.6.0
  
  # 权限管理
  permission_handler: ^11.1.0
  
  # HTTP请求
  dio: ^5.4.0
  
  # 其他工具
  uuid: ^4.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # 代码生成
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700